//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Samochod.h
//  @ Date : 14.05.2024
//  @ Author : 
//
//


#if !defined(_SAMOCHOD_H)
#define _SAMOCHOD_H

#include <string>


class Samochod {
private:
	std::string marka;
	std::string model;
	int rok_produkcji;
    std::string kategoriaSamochodu;
	bool czyDostepny;
    bool stan;
	int cenaZaRezerwacje;
	int cenaZaWynajecie;
public:
    Samochod(std::string marka, std::string model, int rok_produkcji, std::string kategoriaSamochodu, bool czyDostepny, bool stan, int cenaZaRezerwacje, int cenaZaWynajecie);

    std::string getMarka();
    std::string getModel();
    int getRok_produkcji();
    std::string getKategoriaSamochodu();
    bool getCzyDostepny();
    bool getStan();
    int getCenaZaRezerwacje();
    int getCenaZaWynajecie();

    void setStan(bool stan);
    void setCzyDostepny(bool dostepnosc);
};

#endif  //_SAMOCHOD_H
